version: '3'
services:
  vpn_ros:
    build: .
    image: parloma/ros-openvpn-server:intel
    devices:
      - /dev/net/tun
    ports:
      - 9090
      - 1194
    cap_add:
      - NET_ADMIN
    command: roslaunch rosbridge_server rosbridge_websocket.launch

